builds:
    -
        main: ./cmd/pke
        binary: pke
        env:
            - CGO_ENABLED=0
        ldflags: "-s -w -X main.Version={{ .Version }} -X main.CommitHash={{ .ShortCommit }} -X main.BuildDate={{ .Date }}"
        goos:
            - linux
        goarch:
            - amd64

archives:
    -
        name_template: "pke-{{ .Version }}"
        format: binary

checksum:
    name_template: "pke-{{ .Version }}-checksums.txt"

changelog:
    skip: true

nfpms:
    -
        vendor: Banzai Cloud
        maintainer: Banzai Cloud <info@banzaicloud.com>
        homepage: https://banzaicloud.com/
        description: Banzai Cloud Pipeline Kubernetes Engine
        formats:
            - deb
            - rpm
        bindir: /usr/local/bin
        license: Apache 2.0
        file_name_template: "{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}"

blobs:
    -
       provider: s3
       bucket: banzaicloud.com
       region: us-east-1
       folder: "downloads/pke"
