approved = [
    "mit",
    "apache-2.0",
    "bsd-3-clause",
    "bsd-2-clause",
    "mpl-2.0",
]


ignored = [
    "emperror.dev/errors",
    "github.com/ghodss/yaml",
    "go.uber.org/atomic",
    "go.uber.org/multierr",
    "github.com/russross/blackfriday",
    "github.com/gogo/protobuf",
    "sigs.k8s.io/structured-merge-diff/v3",
    "sigs.k8s.io/yaml",
    "k8s.io/klog/v2",
    "sigs.k8s.io/structured-merge-diff/v4",
    "github.com/pkg/errors",
    "gopkg.in/yaml.v2",
    "github.com/spf13/pflag",
    "github.com/spf13/cobra",
    "github.com/Masterminds/semver",
    "github.com/antihax/optional",
    "golang.org/x/net",
    "golang.org/x/oauth2",
    "github.com/avast/retry-go",
    "github.com/PuerkitoBio/rehttp",
    "github.com/pbnjay/memory",
    "github.com/lestrrat-go/backoff",
    "github.com/cpuguy83/go-md2man",
]
