/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipeline
// CreateBackupBucketRequest struct for CreateBackupBucketRequest
type CreateBackupBucketRequest struct {
	Cloud string `json:"cloud"`
	BucketName string `json:"bucketName"`
	SecretId string `json:"secretId"`
	// Optional, if not provided will be set to the name of the cluster
	Prefix string `json:"prefix,omitempty"`
	Location string `json:"location,omitempty"`
	// required only in case of Azure
	StorageAccount string `json:"storageAccount,omitempty"`
	// required only case of Azure
	ResourceGroup string `json:"resourceGroup,omitempty"`
}
