/*
 * Pipeline API
 *
 * Pipeline v0.3.0 swagger
 *
 * API version: 0.17.0
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipeline

type CreateBackupRequest struct {
	Name string `json:"name"`
	Ttl string `json:"ttl"`
	Labels Labels `json:"labels,omitempty"`
	Options BackupOptions `json:"options,omitempty"`
}
