/*
 * Pipeline API
 *
 * Pipeline v0.3.0 swagger
 *
 * API version: 0.17.0
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipeline

type UpdateUserRequest struct {
	GitHubToken string `json:"gitHubToken,omitempty"`
	GitLabToken string `json:"gitLabToken,omitempty"`
}
