/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipeline
// GenericNodePool Generic node pool object for all cluster distributions.
type GenericNodePool struct {
	// Node pool name.
	Name string `json:"name"`
	// Node pool size.
	Size int32 `json:"size"`
	// Node pool labels.
	Labels map[string]string `json:"labels,omitempty"`
}
