/*
 * Pipeline API
 *
 * Pipeline v0.3.0 swagger
 *
 * API version: master
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipeline

type UpdateNodePoolsEks struct {
	InstanceType string `json:"instanceType,omitempty"`
	SpotPrice string `json:"spotPrice,omitempty"`
	Autoscaling bool `json:"autoscaling,omitempty"`
	Count int32 `json:"count,omitempty"`
	MinCount int32 `json:"minCount,omitempty"`
	MaxCount int32 `json:"maxCount,omitempty"`
	Image string `json:"image,omitempty"`
}
