/*
 * Pipeline API
 *
 * Pipeline v0.3.0 swagger
 *
 * API version: master
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipeline

type DeploymentTargetClusterStatus struct {
	Cloud string `json:"cloud,omitempty"`
	ClusterId int32 `json:"clusterId,omitempty"`
	ClusterName string `json:"clusterName,omitempty"`
	Distribution string `json:"distribution,omitempty"`
	Error string `json:"error,omitempty"`
	Stale bool `json:"stale,omitempty"`
	Status string `json:"status,omitempty"`
	Version string `json:"version,omitempty"`
}
