/*
 * Pipeline API
 *
 * Pipeline v0.3.0 swagger
 *
 * API version: master
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipeline

type CreatePkePropertiesClusterTopology struct {
	Network CreatePkePropertiesClusterTopologyNetwork `json:"network"`
	NodePools []NodePoolsPke `json:"nodePools"`
	Kubernetes CreatePkePropertiesClusterTopologyKubernetes `json:"kubernetes"`
	Cri CreatePkePropertiesClusterTopologyCri `json:"cri"`
}
