/*
 * Pipeline API
 *
 * Pipeline v0.3.0 swagger
 *
 * API version: master
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipeline

type PkeOnAzureNodePoolSubnet struct {
	Name string `json:"name,omitempty"`
	// When referencing an already existing subnetwork this field does not need to be specified.
	Cidr string `json:"cidr,omitempty"`
}
