/*
 * Pipeline API
 *
 * Pipeline v0.3.0 swagger
 *
 * API version: master
 * Contact: info@banzaicloud.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipeline

type BackupBucketResponse struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Cloud string `json:"cloud,omitempty"`
	SecretId string `json:"secretId,omitempty"`
	Status string `json:"status,omitempty"`
	InUse bool `json:"inUse,omitempty"`
}
