name: Build PKE
on:
  pull_request:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v1

      - name: Check licenses
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make license-check

      - name: Build code
        run: make build

      - name: Rlease
        run: make release