name: Trigger PKE image build
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  trigger-image-build:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set ref
        id: get-ref
        run: ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Trigger pke-image build
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'banzaicloud',
              repo: 'pke-image',
              workflow_id: 'packer-build.yml',
              ref: 'master',
              inputs: {
                tag: '${{ steps.get-ref.outputs.tag }}'
              }
            })
