name: Release PKE
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: 1.5.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trigger-image-build:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set ref
        id: set-ref
        run: ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Trigger pke-image build
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'banzaicloud',
              repo: 'pke-image',
              workflow_id: 'packer-build.yml',
              ref: 'fix/packer',
              inputs: {
                tag: '${{ steps.set-ref.outputs.tag }}'
              }
            })